name: Deploy to S3 + Invalidate CloudFront

on:
  push:
    branches: [develop]

  workflow_dispatch:
    inputs:
      branch:
        description: "develop"
        required: true
        default: "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create .env.production file
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Deploy to AWS (SSR) with Serverless Framework
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
