name: Deploy Next.js SSR to AWS (Serverless v3)

on:
  push:
    branches: [develop]
  workflow_dispatch:
    inputs:
      branch:
        description: "develop"
        required: true
        default: "develop"

jobs:
  build-and-deploy:
    # 실행 환경
    runs-on: ubuntu-latest

    # 단계(Step)별로 실행될 명령어들
    steps:
      # 1. 코드를 체크아웃(다운로드)
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3. 의존성 패키지 설치
      - name: Install dependencies
        run: npm install

      # 4. Next.js 프로젝트 빌드 (정적 파일 생성)
      - name: Build Next.js project
        run: npm run build

      # 5. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # S3 버킷을 생성한 리전으로 수정

      # 6. 빌드 결과물(out 폴더)을 S3 버킷에 업로드
      - name: Upload to S3
        run: |
          aws s3 sync out/ s3://fitspot-frontend-bucket --delete

      # 7. CloudFront 캐시 무효화 (사용자들이 즉시 변경사항을 볼 수 있게 함)
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
