name: Deploy Next.js SSR to AWS (No SaaS)

on:
  push:
    branches: [develop]
  workflow_dispatch:
    inputs:
      branch:
        description: "develop"
        required: true
        default: "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. 환경변수 생성
      - name: Create .env.production file
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      # 3. Node.js 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. Next.js 빌드 (SSR)
      - name: Build Next.js
        run: npm run build

      # 5. Serverless Components CLI 설치
      - name: Install Serverless Components CLI
        run: npm install -g @serverless/components

      # 6. AWS 인증 설정 (로그인 없이 Components 배포)
      - name: Configure AWS credentials
        run: |
          npx serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY

      # 7. SSR 배포
      - name: Deploy Next.js SSR to AWS
        run: npx components deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
